### ISSUE TITLE
Need to create a vm and set the hostname of the vm

### ISSUE THREAD

**Issue by theoneakta** [robrowan/vmware-guest#1]
I dont see something for that.

When creating vm it takes a default name ubuntu-server

Any help would be appreciated...

**Comment by robrowan** [comment]
So the VM name will be the same as the ansible inventory hostname, you can see this in /tasks/main.yml line 9.

    name: "{{ inventory_hostname|lower }}"

**Comment by theoneakta** [comment]
Hi

I want to set the hostname when creating the vm

**Comment by robrowan** [comment]
This role will create the VM and name it whatever you put in your inventory file.
What does you inventory structure look like?

**Comment by theoneakta** [comment]
well inventory has localhost and vcenter only

**Comment by robrowan** [comment]
Are you new to ansible?
https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

A typical ansible inventory file looks like this:

> [webservers]
> webserver01
> webserver02


This role would create two VMs from this named webserver01 and webserver02
